version: '3.8'

services:
      
  database:
    container_name: moviehouse-database
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: $DB_NAME
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
    ports:
      - $DB_PORT:3306
    volumes:
      - data:/moviehouse-data
    networks:
      - net
      
  backend:
    container_name: moviehouse-service
    restart: unless-stopped
    image: devstoni/moviehouse:0.2.0
    ports:
      - $SERVER_HOST_PORT:80
    networks:
      - net
    depends_on: 
      - database

volumes:
  data:

networks:
  net:
    external: false
